# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d6ff0258bc91445a875885b26560e1a0bc0bdef3e2e562918c799b24735cb57f93a637118411e1e3c53da2fea4b039031d6aa738d5aa0b1d809a363ad42cf0ad

test:
  secret_key_base: 09f6e2b20130d55fd699957cad3a6c5a8bd2d1b64158202aa1d85276abd4b9509de80f3bc6acff898863f48197e68314b73fef0539735f3176025b5b86d96ba2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
